### ISSUE TITLE
Can't seem to be able to setup alerts

### ISSUE THREAD

**Issue by rhymes** [CodeMillIO/Support#2]
Hello,

I just joined and I would like to setup alerts on my favorite languages but as soon as I press "Update alerts" I get this:

![screen shot 2017-06-06 at 10 18 58 am](https://cloud.githubusercontent.com/assets/146201/26820006/9ef9649c-4aa1-11e7-8871-0de0fc777423.png)

![screen shot 2017-06-06 at 10 19 07 am](https://cloud.githubusercontent.com/assets/146201/26820013/a56432a8-4aa1-11e7-918c-eeab570ea66a.png)

**Comment by shaharsol** [comment]
Thanks for the notification, fixed!
